const OBJECT_TYPE = Object.freeze({
  COLUMN_HEADER: "COLUMN_HEADER",
  COLUMN_RESIZER: "COLUMN_RESIZER",
  ROW_HEADER: "ROW_HEADER",
  ROW_RESIZER: "ROW_RESIZER",
  CELL: "CELL"
});


export default {
  OBJECT_TYPE
};
